config/routes.rb
Rails.application.routes.draw do
  resources :topics, only: [:index, :show]

  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout', sign_up: 'register' }
  root to: 'pages#home'

  resources :projects, except: [:show] do
    # when you see projects/sort do this instead
    put :sort, on: :collection
  end

  get 'project/:id', to: 'projects#show', as: 'project_show'

  get 'about', to: 'pages#about'
  get 'contact', to: 'pages#contact'
  get 'tech-news', to: 'pages#tech_news'

  resources :blogs do
    member do 
      get :toggle_status
    end
  end

  mount ActionCable.server => '/cable'

end

app/models/project.rb
class Project < ApplicationRecord
    has_many :technologies
    accepts_nested_attributes_for :technologies,
                                  allow_destroy: true,
                                  reject_if: lambda { |attrs| attrs['name'].blank? }

    validates_presence_of :title, :body

    # mount_uploader tells project model it needs to call carrierwave
    # apply uploader to thumb_image/main_image, use Project Uploader
    mount_uploader :thumb_image, ProjectUploader
    mount_uploader :main_image, ProjectUploader

    # Custom Scopes in 2 formats
    def self.react
        where(subtitle: 'React')
    end

    def self.by_position
      order("position ASC")
    end

    scope :ruby_on_rails_project_items, -> { where(subtitle: 'Ruby on Rails') }
    # end scopes

end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :set_project, only: [:edit, :update, :show, :destroy]
  layout "project"
  access all: [:show, :index], user: {except: [:destroy, :new, :create, :update, :edit, :sort]}, site_admin: :all

  def index
    @project_items = Project.by_position
  end

  def sort
    params[:order].each do |key, value|
      Project.find(value[:id]).update(position: value[:position])
    end

    render body: nil
  end

  def show
  end

  def new
    @project = Project.new
  end

  def create
    @project = Project.new(project_params)

    respond_to do |format|
      if @project.save
        format.html { redirect_to projects_path, notice: "Your project is now live." }
      else
        format.html { render :new }
      end
    end
  end

  def edit
  end

  def update
    respond_to do |format|
      if @project.update(project_params)
        format.html { redirect_to projects_path, notice: "The record successfully updated." }
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Project was removed.' }
    end
  end

  private

  def project_params
    params.require(:project).permit(:title, 
                                    :subtitle, 
                                    :body, 
                                    :main_image,
                                    :thumb_image,
                                    technologies_attributes: [:id, :name, :_destroy]
                                    )
  end

  def set_project
    @project = Project.find(params[:id])
  end

end

app/helpers/projects_helper.rb
module ProjectsHelper
  def image_generator(height:, width:)
    "http://placehold.it/#{height}x#{width}"
  end

  def project_img img, type
    if img.model.main_image? || img.model.thumb_image?
      img
    elsif type == 'thumb'
      image_generator(height: '350', width: '200')
    elsif type == 'main'
      image_generator(height: '600', width: '400')
    end
  end
end


        

app/views/projects/_form.html.erb
<%= form_with(model: @project, local: true) do |f| %>
  <% if @project.errors.any? %>
    <% @project.errors.full_messages.each do |error| %>
      <%= alert_generator error %>
    <% end %>
  <% end %>

  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :title %>
        <%= f.text_field :title, class: 'form-control' %>
      </div>

      <div class="form-group">
        <%= f.label :subtitle %>
        <%= f.text_field :subtitle, class: 'form-control' %>
      </div>

      <div class="form-group">
        <label class="btn btn-outline-primary">
          Upload a main image file <%= f.file_field :main_image, style: 'display:none;' %>
        </label>
      </div>
      
      <div class="form-group">
        <label class="btn btn-outline-primary">
          Upload a thumb image file <%= f.file_field :thumb_image, style: 'display:none;' %>
        </label>
      </div>
    </div>

    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :body %>
        <%= f.text_area :body, class: 'form-control', rows: 13 %>
      </div>
    </div>
  </div>

  <hr>

  <div class="col-md-12">
    <h2>Technologies Used:</h2>
    <div>
      <%= f.fields_for :technologies do |technology_form| %>
        <%= render 'technology_fields', f: technology_form %>
      <% end %>

      <div>
        <%= link_to_add_association 'Add Technology', f, :technologies %>
      </div>
    </div>

    <div class="form-group">
      <%= f.submit 'Submit', class: 'btn btn-outline-primary btn-block' %>
    </div>
  </div>
<% end %>

app/views/projects/_project_item.html.erb
<div class="col-md-4 card-container" data-id="<%= project_item.id %>">
  <div class="card mb-4 box-shadow">
    <%= image_tag project_img(project_item.thumb_image, 'thumb'), width: '100%' %>
    <div class="card-body">
      <p class="card-text">
        <span>
          <%= link_to project_item.title, project_show_path(project_item) %>
        </span>
        <%= project_item.subtitle %>
      </p>

      <!-- Do I want this section? -->
      <!-- <div class="d-flex justify-content-between align-items-center">
        <div class="btn-group">
          <button type="button" class="btn btn-sm btn-outline-secondary">View</button>
          <button type="button" class="btn btn-sm btn-outline-secondary">Edit</button>
        </div>
        <small class="text-muted">9 mins</small>
      </div> --> 
    </div>
  </div>
</div>

app/views/projects/_technology_fields.html.erb
<div class="form-group nested-fields">
  <%= f.label :name %>
  <%= f.text_field :name, class: 'form-control' %>
  <%= link_to_remove_association 'Remove Technology', f %>
</div>

app/views/projects/edit.html.erb
<div class="container project-container">
  <h1>Edit Project</h1>

  <%= render 'form', project: @project %>
</div>

app/views/projects/index.html.erb
<div class="album py-5 bg-light">
  <div class="container">
    <%= source_helper("alert alert-warning") %>
    <div class="row <%= "sortable" if logged_in?(:site_admin) %>">

      <%= render partial: 'project_item', collection: @project_items %>

    </div>
  </div>
</div>

app/views/projects/new.html.erb
<div class="container project-container">
  <h1>Create a new Project</h1>
  <%= render 'form', project: @project %>
</div>

app/views/projects/show.html.erb
<div class="container project-container">
  <div class="row">
    <div class="col-md-7">
      <%= image_tag project_img(@project.main_image, 'main'), width: '100%' %>
    </div>
    
    <div class="col-md-5">
      <h1><%= @project.title %></h1>

      <hr>

      <em><%= @project.subtitle %></em>

      <p><%= @project.body %></p>

      <hr>

      <h3>Technologies Used:</h3>

      <% @project.technologies.each do |t| %>
          <p><%= t.name %></p>
      <% end %>

      <% if logged_in?(:site_admin) %>
        <div>
          <%= link_to "Edit Item", edit_project_path(@project), class: 'btn btn-warning' %>
        </div>
      <% end %>

    </div>
  </div>
</div>